# Generated by Django 4.1.1 on 2022-09-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='fecha_inauguracion',
            field=models.DateField(),
        ),
    ]
