# Generated by Django 4.1.1 on 2022-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0004_remove_sede_estado_id_remove_sede_pais_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='estado',
            field=models.CharField(choices=[('SD', 'SUSPENDIDO DEFINITIVAMENTE'), ('DI', 'DISPONIBLE'), ('EM', 'EN MANTENIMIENTO'), ('ND', 'NO DISPONIBLE'), ('ST', 'SUSPENDIDO TEMPORALMENTE')], default='DI', max_length=2),
        ),
    ]
