# Generated by Django 4.1.1 on 2022-10-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0005_alter_sede_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='clima',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='humedad',
            field=models.CharField(max_length=4),
        ),
    ]
