# Generated by Django 4.1.1 on 2022-10-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appArbitro', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='tipo_arbitro',
            field=models.CharField(choices=[('P', 'PRINCIPAL'), ('J', 'JUEZ DE LINEA'), ('C', 'CUARTO HOMBRE'), ('V', 'VAR')], default='P', max_length=1),
        ),
    ]
