# Generated by Django 4.1.1 on 2022-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('contrato_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valor', models.FloatField()),
                ('tipo_contrato', models.CharField(choices=[('P', 'Prestamo'), ('C', 'Compra'), ('L', 'Libre'), ('R', 'Renovacion'), ('S', 'Seleccion')], default='C', max_length=1)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('persona_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('estatura', models.FloatField()),
                ('peso', models.FloatField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'persona',
            },
        ),
        migrations.CreateModel(
            name='tipo_persona',
            fields=[
                ('tipo_persona_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'tipo_persona',
            },
        ),
    ]
