# Generated by Django 4.1.1 on 2022-10-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0003_alter_persona_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('P', 'PRÉSTAMO'), ('C', 'COMPRA'), ('L', 'LIBRE'), ('R', 'RENOVACIÓN'), ('S', 'SELECCIÓN')], default='C', max_length=1),
        ),
    ]
