# Generated by Django 4.1.1 on 2022-10-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0004_alter_contrato_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jugador/foto/'),
        ),
    ]
