# Generated by Django 4.1.1 on 2022-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='vestimenta',
        ),
        migrations.AddField(
            model_name='equipo',
            name='vestimenta_alterna',
            field=models.ImageField(blank=True, null=True, upload_to='equipo/vestimenta_secundaria/'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='vestimenta_principal',
            field=models.ImageField(blank=True, null=True, upload_to='equipo/vestimenta_principal/'),
        ),
    ]
