# Generated by Django 4.1.1 on 2022-10-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0004_equipo_presidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='equipo/portada/'),
        ),
    ]
