# Generated by Django 4.1.1 on 2022-09-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('S', 'Supervisor de Calidad'), ('D', 'Desarrollador'), ('I', 'Diseñador'), ('A', 'Analista')], default='D', max_length=1),
        ),
    ]
