# Generated by Django 4.1.1 on 2022-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='sigla',
            field=models.CharField(default='', max_length=3),
        ),
    ]
