# Generated by Django 4.1.1 on 2022-10-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0003_pais_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicion',
            name='deporte_id',
            field=models.ForeignKey(db_column='deporte_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.deporte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competicion',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
