# Generated by Django 4.1.1 on 2022-10-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0004_competicion_deporte_id_competicion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicion',
            name='fecha_fin',
            field=models.DateField(blank=True, default='1990-12-12', null=True),
        ),
        migrations.AddField(
            model_name='competicion',
            name='fecha_inicio',
            field=models.DateField(blank=True, default='1990-12-12', null=True),
        ),
    ]
